plugins:
  discourse_donations_enabled:
    default: false
    client: true
  discourse_donations_secret_key:
    default: ''
    client: false
    secret: true
  discourse_donations_public_key:
    default: ''
    client: true
  discourse_donations_subscription_required:
    client: true
    default: false
  discourse_donations_description:
    client: true
    default: ''
  discourse_donations_currency:
    client: true
    default: 'USD'
  discourse_donations_zip_code:
    default: false
    client: true
  discourse_donations_billing_address:
    default: true
    client: true
  discourse_donations_reward_badge_name:
    client: false
    default: 'Donation'
  discourse_donations_reward_group_name:
    client: false
    default: 'Donation'
  discourse_donations_page_heading:
    client: true
    default: 'Make a Donation'
  discourse_donations_page_description:
    client: true
    default: ''
  discourse_donations_enable_transaction_fee:
    client: true
    default: false
  discourse_donations_transaction_fee_fixed:
    client: true
    default: 0.3
  discourse_donations_transaction_fee_percent:
    client: true
    default: 0.029
  discourse_donations_custom_amount:
    client: true
    default: false
  discourse_donations_amounts:
    client: true
    type: list
    default: '1|2|5|10|20|50'
    regex: "^[0-9\\|]+$"
    regex_error: "site_settings.errors.discourse_donations_amount_must_be_number"
  discourse_donations_types:
    client: true
    type: list
    default: 'once|month'
    choices:
      - year
      - month
      - week
      - once
  discourse_donations_causes:
    client: true
    type: list
    default: ''
  discourse_donations_causes_categories:
    client: true
    type: category_list
    default: ''
  discourse_donations_cause_category:
    client: true
    default: false
  discourse_donations_cause_required:
    client: true
    default: false
  discourse_donations_cause_month:
    client: true
    default: false